// BarberFlix — content & data
// Stored on window so all babel scripts can read it.

const POSTERS = {
  degrade: {
    gradient: "radial-gradient(ellipse at 30% 20%, #2a0608 0%, #0a0203 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(255,31,58,0.35) 70%, rgba(255,31,58,0.6) 100%)",
    glyph: "01",
  },
  social: {
    gradient: "radial-gradient(ellipse at 70% 30%, #1c2336 0%, #0a0e18 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(160,180,210,0.2) 80%, rgba(220,225,235,0.35) 100%)",
    glyph: "02",
  },
  barba: {
    gradient: "radial-gradient(ellipse at 40% 70%, #3a210a 0%, #160a02 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(212,175,55,0.18) 80%, rgba(212,175,55,0.4) 100%)",
    glyph: "03",
  },
  pigmentacao: {
    gradient: "radial-gradient(ellipse at 60% 40%, #1a0826 0%, #0a0312 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(170,80,210,0.25) 80%, rgba(140,60,200,0.45) 100%)",
    glyph: "04",
  },
  maquina: {
    gradient: "radial-gradient(ellipse at 50% 60%, #0c1e2a 0%, #060f17 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(80,180,220,0.18) 80%, rgba(60,160,220,0.4) 100%)",
    glyph: "05",
  },
  atendimento: {
    gradient: "radial-gradient(ellipse at 30% 30%, #2a1c08 0%, #120a02 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(212,175,55,0.25) 80%, rgba(212,175,55,0.5) 100%)",
    glyph: "06",
  },
  marketing: {
    gradient: "radial-gradient(ellipse at 70% 70%, #2a0a1c 0%, #100208 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(255,80,140,0.2) 80%, rgba(220,40,100,0.4) 100%)",
    glyph: "07",
  },
  dinheiro: {
    gradient: "radial-gradient(ellipse at 50% 30%, #0a2418 0%, #021008 60%, #000 100%)",
    accent: "linear-gradient(180deg, transparent 0%, rgba(80,180,120,0.18) 80%, rgba(60,160,100,0.35) 100%)",
    glyph: "08",
  },
};

const SERIES = [
  {
    id: "degrade-perfeito",
    title: "Degradê Perfeito",
    subtitle: "A arte do fade impecável",
    mentor: "Rafael Costa",
    mentorTitle: "Master Barber · São Paulo",
    season: "T1",
    year: 2025,
    episodes: 8,
    duration: "3h 42min",
    level: "Avançado",
    rating: 4.9,
    students: 12480,
    vip: false,
    new: true,
    progress: 0.62,
    poster: "degrade",
    category: "Técnicas de Corte",
    tags: ["Fade", "Skin Fade", "Drop Fade", "Marcação"],
    synopsis: "Domine a técnica de degradê em todas as suas variações. Da marcação inicial à transição perfeita, cada movimento desconstruído em detalhe cirúrgico. Inclui análise em câmera lenta, ângulos múltiplos e correção de erros em tempo real.",
    episodeList: [
      { n: 1, title: "Marcação Inicial",         duration: "24:18", progress: 1.00, synopsis: "Estabelecendo as linhas-guia. Como ler o crescimento natural do cabelo e definir as alturas do degradê antes de qualquer corte.", thumb: "degrade-1" },
      { n: 2, title: "Transição da Sombra",      duration: "31:05", progress: 1.00, synopsis: "O segredo está na transição. Trabalho com pente e máquina para criar a difusão perfeita entre as zonas.", thumb: "degrade-2" },
      { n: 3, title: "Acabamento Profissional",  duration: "28:42", progress: 0.45, synopsis: "Disfarce com tesoura, navalha e produto. Como entregar um corte que parece esculpido.",                                  thumb: "degrade-3" },
      { n: 4, title: "Erros que Arruinam o Degradê", duration: "22:10", progress: 0, synopsis: "Os 7 erros mais comuns e como evitá-los — direto da bancada de quem corta há 15 anos.",                                 thumb: "degrade-4" },
      { n: 5, title: "Fade em Cabelos Crespos",  duration: "29:34", progress: 0, synopsis: "Adaptação técnica para texturas afro. Pressão, ângulo e produto certos para cada padrão.",                                    thumb: "degrade-5" },
      { n: 6, title: "Drop Fade Avançado",       duration: "26:50", progress: 0, synopsis: "A curva descendente que define o estilo moderno. Geometria aplicada ao corte.",                                                thumb: "degrade-6" },
      { n: 7, title: "Skin Fade na Navalha",     duration: "33:12", progress: 0, synopsis: "Levando o zero ao limite. Técnica de raspagem segura e simétrica.",                                                            thumb: "degrade-7" },
      { n: 8, title: "Estúdio: Sessão Completa", duration: "47:08", progress: 0, synopsis: "Atendimento real do começo ao fim. Veja cada decisão técnica em contexto.",                                                    thumb: "degrade-8" },
    ],
  },
  {
    id: "corte-social-premium",
    title: "Corte Social Premium",
    subtitle: "O clássico, refinado",
    mentor: "Lucas Ferreira",
    mentorTitle: "Barbeiro Executivo · Pinheiros",
    season: "T1",
    year: 2025,
    episodes: 6,
    duration: "2h 58min",
    level: "Intermediário",
    rating: 4.8,
    students: 8240,
    vip: false,
    new: false,
    progress: 0.12,
    poster: "social",
    category: "Cortes Clássicos",
    tags: ["Social", "Executivo", "Clássico", "Atendimento VIP"],
    synopsis: "O corte que define autoridade. Técnica clássica adaptada para o cliente moderno — executivos, advogados, médicos. Aprenda a precificar, atender e entregar o resultado que esse público exige.",
    episodeList: [
      { n: 1, title: "Anatomia do Corte Social",      duration: "26:00", progress: 0.30, synopsis: "Estrutura, proporção e linhas que sustentam o corte clássico.", thumb: "social-1" },
      { n: 2, title: "Tesoura sobre Pente",           duration: "32:15", progress: 0, synopsis: "Técnica fundamental, executada com leveza.", thumb: "social-2" },
      { n: 3, title: "Risco e Definição",             duration: "21:48", progress: 0, synopsis: "O traço que finaliza. Navalha, ângulo e firmeza.", thumb: "social-3" },
      { n: 4, title: "Finalização com Pomada",        duration: "19:30", progress: 0, synopsis: "Produto, separação e modelagem.", thumb: "social-4" },
      { n: 5, title: "Adaptações por Tipo de Rosto",  duration: "28:42", progress: 0, synopsis: "Oval, quadrado, redondo — ajustes técnicos.", thumb: "social-5" },
      { n: 6, title: "Atendimento de Alto Padrão",    duration: "30:50", progress: 0, synopsis: "Postura, ritual e o que faz o cliente voltar.", thumb: "social-6" },
    ],
  },
  {
    id: "barba-profissional",
    title: "Barba Profissional",
    subtitle: "Esculpindo identidade",
    mentor: "André Moretti",
    mentorTitle: "Master Barber · Rio de Janeiro",
    season: "T1",
    year: 2025,
    episodes: 7,
    duration: "3h 18min",
    level: "Intermediário",
    rating: 4.9,
    students: 10120,
    vip: true,
    new: false,
    progress: 0.88,
    poster: "barba",
    category: "Barba",
    tags: ["Barba", "Navalha", "Modelagem", "Pelo Encravado"],
    synopsis: "A barba certa redesenha o rosto. Aprenda a desenhar contornos, escolher o estilo certo para cada cliente e dominar a navalha com segurança cirúrgica.",
    episodeList: [
      { n: 1, title: "Leitura do Rosto",        duration: "23:50", progress: 1.00, synopsis: "O mapa antes do corte.", thumb: "barba-1" },
      { n: 2, title: "Desenho de Contornos",    duration: "27:12", progress: 1.00, synopsis: "Linha bochecha, linha pescoço, bigode.", thumb: "barba-2" },
      { n: 3, title: "Navalha — Segurança",     duration: "29:38", progress: 1.00, synopsis: "Postura, pegada, pressão.", thumb: "barba-3" },
      { n: 4, title: "Modelagem com Tesoura",   duration: "25:20", progress: 1.00, synopsis: "Volume controlado.", thumb: "barba-4" },
      { n: 5, title: "Hidratação e Cuidado",    duration: "18:45", progress: 1.00, synopsis: "Pré e pós, óleo e bálsamo.", thumb: "barba-5" },
      { n: 6, title: "Barbas Curtas vs. Cheias",duration: "31:02", progress: 0.55, synopsis: "Técnicas que mudam tudo.", thumb: "barba-6" },
      { n: 7, title: "Casos Difíceis",          duration: "32:30", progress: 0, synopsis: "Pelo encravado, falhas, assimetria.", thumb: "barba-7" },
    ],
  },
  {
    id: "pigmentacao-masculina",
    title: "Pigmentação Masculina",
    subtitle: "A nova era da barba e do couro",
    mentor: "Vitor Lacerda",
    mentorTitle: "Especialista em Tricopigmentação",
    season: "T1",
    year: 2025,
    episodes: 9,
    duration: "4h 12min",
    level: "Avançado",
    rating: 4.8,
    students: 5840,
    vip: true,
    new: true,
    progress: 0,
    poster: "pigmentacao",
    category: "Estética Masculina",
    tags: ["Tricopigmentação", "Densidade", "Calvície", "Procedimento"],
    synopsis: "O procedimento que está transformando barbearias em centros de estética masculina. Da biossegurança ao traço — tudo o que você precisa para oferecer pigmentação com qualidade clínica.",
    episodeList: [
      { n: 1, title: "Introdução e Biossegurança", duration: "26:00", progress: 0, synopsis: "Fundamentos do procedimento.", thumb: "pig-1" },
      { n: 2, title: "Equipamentos e Pigmentos",   duration: "22:30", progress: 0, synopsis: "Escolhendo o ferramental.", thumb: "pig-2" },
      { n: 3, title: "Densidade Capilar",          duration: "31:45", progress: 0, synopsis: "Simulando volume real.", thumb: "pig-3" },
      { n: 4, title: "Disfarce de Cicatrizes",     duration: "28:12", progress: 0, synopsis: "Casos sensíveis e técnica precisa.", thumb: "pig-4" },
      { n: 5, title: "Barba — Preenchimento",      duration: "25:40", progress: 0, synopsis: "Falhas e simetria.", thumb: "pig-5" },
      { n: 6, title: "Procedimento Completo",      duration: "42:18", progress: 0, synopsis: "Sessão integral em estúdio.", thumb: "pig-6" },
      { n: 7, title: "Pós-procedimento",           duration: "19:30", progress: 0, synopsis: "Cuidados e retoque.", thumb: "pig-7" },
      { n: 8, title: "Precificação e Pacotes",     duration: "21:55", progress: 0, synopsis: "Modelagem comercial.", thumb: "pig-8" },
      { n: 9, title: "Casos Reais",                duration: "34:10", progress: 0, synopsis: "Antes e depois com análise técnica.", thumb: "pig-9" },
    ],
  },
  {
    id: "tecnicas-de-maquina",
    title: "Técnicas de Máquina",
    subtitle: "Domine cada engrenagem",
    mentor: "Thiago Almeida",
    mentorTitle: "Educador Wahl Pro",
    season: "T1",
    year: 2024,
    episodes: 5,
    duration: "2h 14min",
    level: "Iniciante",
    rating: 4.7,
    students: 14200,
    vip: false,
    new: false,
    progress: 0.30,
    poster: "maquina",
    category: "Fundamentos",
    tags: ["Máquina", "Lâminas", "Ajustes", "Manutenção"],
    synopsis: "Da escolha da máquina à manutenção semanal. Tudo o que define um profissional pela ferramenta.",
    episodeList: [
      { n: 1, title: "Tipos de Máquina",       duration: "18:20", progress: 1.00, synopsis: "Trimmer, máquina principal, foil shaver.", thumb: "maq-1" },
      { n: 2, title: "Lâminas e Pentes",       duration: "24:10", progress: 0.50, synopsis: "Decodificando os números.", thumb: "maq-2" },
      { n: 3, title: "Ajuste e Calibragem",    duration: "21:45", progress: 0, synopsis: "Zero perfeito, lâmina viva.", thumb: "maq-3" },
      { n: 4, title: "Manutenção e Limpeza",   duration: "16:30", progress: 0, synopsis: "Rotina que dobra a vida útil.", thumb: "maq-4" },
      { n: 5, title: "Erros de Iniciantes",    duration: "33:08", progress: 0, synopsis: "O que ninguém te conta no curso básico.", thumb: "maq-5" },
    ],
  },
  {
    id: "atendimento-e-fidelizacao",
    title: "Atendimento e Fidelização",
    subtitle: "O cliente que volta",
    mentor: "Camila Reis",
    mentorTitle: "Consultora de CX para Barbearias",
    season: "T1",
    year: 2025,
    episodes: 6,
    duration: "2h 40min",
    level: "Todos",
    rating: 4.9,
    students: 7320,
    vip: false,
    new: false,
    progress: 0,
    poster: "atendimento",
    category: "Negócios",
    tags: ["Atendimento", "Fidelização", "Experiência", "CX"],
    synopsis: "Técnica é só metade. O cliente volta pelo que sentiu. Construa um ritual de atendimento que faz da sua barbearia uma referência.",
    episodeList: [
      { n: 1, title: "O Ritual de Recepção",  duration: "22:15", progress: 0, synopsis: "Os primeiros 30 segundos definem tudo.", thumb: "at-1" },
      { n: 2, title: "Linguagem e Postura",   duration: "26:48", progress: 0, synopsis: "Como você fala vale o que você corta.", thumb: "at-2" },
      { n: 3, title: "Cardápio de Serviços",  duration: "24:30", progress: 0, synopsis: "Pacotes, upsell, percepção de valor.", thumb: "at-3" },
      { n: 4, title: "Pós-atendimento",       duration: "19:20", progress: 0, synopsis: "O contato que faz o cliente voltar.", thumb: "at-4" },
      { n: 5, title: "Lidando com Reclamações",duration: "28:00", progress: 0, synopsis: "Transformando erro em fidelidade.", thumb: "at-5" },
      { n: 6, title: "Programa de Fidelidade",duration: "39:42", progress: 0, synopsis: "Estratégia que funciona em barbearia.", thumb: "at-6" },
    ],
  },
  {
    id: "marketing-para-barbeiros",
    title: "Marketing para Barbeiros",
    subtitle: "De cadeira vazia a agenda lotada",
    mentor: "Bruno Tavares",
    mentorTitle: "Estrategista Digital · 200 barbearias",
    season: "T1",
    year: 2025,
    episodes: 8,
    duration: "3h 50min",
    level: "Intermediário",
    rating: 4.8,
    students: 11680,
    vip: true,
    new: true,
    progress: 0,
    poster: "marketing",
    category: "Negócios",
    tags: ["Instagram", "Conteúdo", "Tráfego", "Branding"],
    synopsis: "Instagram, tráfego pago, branding. O método completo para encher sua agenda com o cliente que paga o preço que você quer cobrar.",
    episodeList: [
      { n: 1, title: "Posicionamento de Marca",       duration: "28:12", progress: 0, synopsis: "Quem você quer atender define tudo.", thumb: "mk-1" },
      { n: 2, title: "Foto e Vídeo na Barbearia",     duration: "32:40", progress: 0, synopsis: "Conteúdo que vende, com celular.", thumb: "mk-2" },
      { n: 3, title: "Roteiros que Funcionam",        duration: "24:18", progress: 0, synopsis: "Modelos prontos, adaptáveis.", thumb: "mk-3" },
      { n: 4, title: "Instagram — Algoritmo",         duration: "29:30", progress: 0, synopsis: "Como aparecer pra quem importa.", thumb: "mk-4" },
      { n: 5, title: "Tráfego Pago — Setup",          duration: "31:22", progress: 0, synopsis: "Anúncios que enchem a agenda.", thumb: "mk-5" },
      { n: 6, title: "Google Meu Negócio",            duration: "18:45", progress: 0, synopsis: "O canal grátis que ninguém usa direito.", thumb: "mk-6" },
      { n: 7, title: "Métricas que Importam",         duration: "26:50", progress: 0, synopsis: "O que medir, o que ignorar.", thumb: "mk-7" },
      { n: 8, title: "Plano de 90 Dias",              duration: "38:15", progress: 0, synopsis: "Implementação semana a semana.", thumb: "mk-8" },
    ],
  },
  {
    id: "como-ganhar-dinheiro-com-barbearia",
    title: "Como Ganhar Dinheiro com Barbearia",
    subtitle: "O modelo de negócio por trás da cadeira",
    mentor: "Eduardo Prado",
    mentorTitle: "Sócio · 14 unidades · 6 estados",
    season: "T1",
    year: 2025,
    episodes: 10,
    duration: "5h 22min",
    level: "Todos",
    rating: 5.0,
    students: 9420,
    vip: true,
    new: false,
    progress: 0,
    poster: "dinheiro",
    category: "Negócios",
    tags: ["Finanças", "Precificação", "Expansão", "Sócio"],
    synopsis: "Precificação, custos, sócios, expansão. A engenharia financeira que transforma uma barbearia em um negócio de 7 dígitos.",
    episodeList: [
      { n: 1, title: "DRE da Barbearia",         duration: "28:50", progress: 0, synopsis: "Entendendo o dinheiro de verdade.", thumb: "din-1" },
      { n: 2, title: "Precificação Estratégica", duration: "32:18", progress: 0, synopsis: "Quanto cobrar — e por quê.", thumb: "din-2" },
      { n: 3, title: "Custo por Cliente",        duration: "24:30", progress: 0, synopsis: "Métrica que muda decisões.", thumb: "din-3" },
      { n: 4, title: "Comissão vs. Fixo",        duration: "29:42", progress: 0, synopsis: "Modelos de remuneração.", thumb: "din-4" },
      { n: 5, title: "Estoque e Produto",        duration: "21:15", progress: 0, synopsis: "Margem extra invisível.", thumb: "din-5" },
      { n: 6, title: "Contratando Barbeiros",    duration: "33:00", progress: 0, synopsis: "Filtros e contrato.", thumb: "din-6" },
      { n: 7, title: "Segunda Unidade",          duration: "37:45", progress: 0, synopsis: "Quando, onde, como.", thumb: "din-7" },
      { n: 8, title: "Franquia vs. Próprio",     duration: "30:20", progress: 0, synopsis: "Decisão estratégica.", thumb: "din-8" },
      { n: 9, title: "Sociedade",                duration: "42:08", progress: 0, synopsis: "Contratos e armadilhas.", thumb: "din-9" },
      { n:10, title: "Cases — 7 dígitos",        duration: "43:12", progress: 0, synopsis: "Três barbearias, três caminhos.", thumb: "din-10" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Upcoming releases — locked, landscape, "coming soon" treatment
// ─────────────────────────────────────────────────────────────────────────────
const UPCOMING = [
  {
    id: "colorimetria-masculina",
    title: "Colorimetria Masculina",
    subtitle: "A ciência da cor para barbeiros",
    teaser: "Da neutralização do amarelo ao platinado seguro. Química do cabelo masculino sem mistério.",
    mentor: "Letícia Vinhas",
    mentorTitle: "Color Master · Cabelos & Cores",
    episodes: 8,
    duration: "3h 40min",
    status: "Em breve",
    statusLabel: "DISPONÍVEL EM BREVE",
    releaseDate: "Junho 2026",
    poster: "pigmentacao",
    accentHue: 280,
    tags: ["Colorimetria", "Decoloração", "Tonalização", "Química"],
  },
  {
    id: "como-lotar-sua-agenda",
    title: "Como Lotar Sua Agenda",
    subtitle: "De 30% a 100% de ocupação em 90 dias",
    teaser: "O método replicável que tirou 14 barbearias do azul. Tráfego, retenção e oferta.",
    mentor: "Bruno Tavares",
    mentorTitle: "Estrategista Digital · 200 barbearias",
    episodes: 10,
    duration: "4h 50min",
    status: "Próximo Lançamento",
    statusLabel: "PRÓXIMO LANÇAMENTO",
    releaseDate: "12 Junho 2026",
    poster: "marketing",
    accentHue: 340,
    tags: ["Agenda", "Retenção", "Oferta", "Funil"],
  },
  {
    id: "escovacao-profissional",
    title: "Escovação Profissional",
    subtitle: "Finalização que vende o corte",
    teaser: "A finalização que diferencia o barbeiro comum do master. Produto, ferramenta, técnica.",
    mentor: "André Moretti",
    mentorTitle: "Master Barber · Rio de Janeiro",
    episodes: 6,
    duration: "2h 30min",
    status: "Em desenvolvimento",
    statusLabel: "EM DESENVOLVIMENTO",
    releaseDate: "Julho 2026",
    poster: "social",
    accentHue: 210,
    tags: ["Escovação", "Modelagem", "Finalização", "Produto"],
  },
  {
    id: "navalha-clube",
    title: "Navalha de Clube",
    subtitle: "A arte do barbear clássico",
    teaser: "Do amolar à toalha quente. O ritual completo do barbear de navalha, desconstruído.",
    mentor: "Antonio Salvatore",
    mentorTitle: "Master Barber · 30 anos de bancada",
    episodes: 7,
    duration: "3h 12min",
    status: "Em breve",
    statusLabel: "DISPONÍVEL EM BREVE",
    releaseDate: "Agosto 2026",
    poster: "barba",
    accentHue: 36,
    tags: ["Navalha", "Barbear", "Toalha quente", "Ritual"],
  },
  {
    id: "cortes-classicos-revisitados",
    title: "Cortes Clássicos Revisitados",
    subtitle: "Pompadour, Side Part, Quiff — versões 2026",
    teaser: "A releitura técnica dos clássicos. Cada corte com 3 variações modernas.",
    mentor: "Lucas Ferreira",
    mentorTitle: "Barbeiro Executivo · Pinheiros",
    episodes: 9,
    duration: "4h 18min",
    status: "Em breve",
    statusLabel: "DISPONÍVEL EM BREVE",
    releaseDate: "Setembro 2026",
    poster: "degrade",
    accentHue: 0,
    tags: ["Pompadour", "Side Part", "Quiff", "Clássico"],
  },
  {
    id: "psicologia-do-cliente",
    title: "Psicologia do Cliente",
    subtitle: "Vender mais sem parecer que está vendendo",
    teaser: "Gatilhos, escuta ativa e o ritual que faz o cliente comprar antes de você ofertar.",
    mentor: "Camila Reis",
    mentorTitle: "Consultora de CX para Barbearias",
    episodes: 6,
    duration: "2h 48min",
    status: "Em desenvolvimento",
    statusLabel: "EM DESENVOLVIMENTO",
    releaseDate: "Outubro 2026",
    poster: "atendimento",
    accentHue: 42,
    tags: ["Vendas", "Psicologia", "Atendimento", "Upsell"],
  },
];

// Convenience derived lists
const CONTINUE_WATCHING = SERIES.filter(s => s.progress > 0 && s.progress < 1);
const NEW_RELEASES      = SERIES.filter(s => s.new);
const VIP_ONLY          = SERIES.filter(s => s.vip);
const TRENDING          = [SERIES[0], SERIES[2], SERIES[7], SERIES[3], SERIES[6], SERIES[1]];

// User profile
const USER = {
  name: "Carlos Andrade",
  initials: "CA",
  email: "carlos.andrade@gmail.com",
  plan: "VIP Black",
  memberSince: "Março 2024",
  streak: 18,           // dias consecutivos
  hoursWatched: 47.5,
  coursesCompleted: 3,
  coursesInProgress: 4,
  certificates: 3,
  level: 7,
  xp: 4280,
  xpNextLevel: 5000,
};

// Reviews for series detail
const REVIEWS = [
  { name: "Diego Santos",   initials: "DS", rating: 5, when: "2 dias atrás", text: "Conteúdo de outro nível. A explicação da transição da sombra valeu o ano inteiro de assinatura." },
  { name: "Felipe Moura",   initials: "FM", rating: 5, when: "1 semana atrás", text: "Já trabalho há 8 anos e ainda saí com técnica nova. Recomendo para qualquer barbeiro sério." },
  { name: "Renato Lima",    initials: "RL", rating: 4, when: "2 semanas atrás", text: "Excelente, só sinto falta de mais casos em cabelo crespo no episódio 1 — mas o resto compensa." },
];

// Make available globally
window.BFData = { SERIES, POSTERS, CONTINUE_WATCHING, NEW_RELEASES, VIP_ONLY, TRENDING, USER, REVIEWS, UPCOMING };
